image:
  repository: nvcr.io/nvidian/gpu-health/gpuhealth-agent
  tag: "0.0.8"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nvcr-pull-secret

hostPID: true
runtimeClassName: nvidia

securityContext:
  privileged: true
  runAsUser: 0

env:
  NVIDIA_VISIBLE_DEVICES: all
  NVIDIA_DRIVER_CAPABILITIES: utility
  DCGM_ADDRESS: nvidia-dcgm.gpu-operator.svc:5555

logLevel: warn
listenAddress: 0.0.0.0:15133
components: all

enroll:
  enabled: false
  endpoint: ""
  tokenSecretName: ""
  tokenSecretKey: "token"
  tokenValue: ""
  securityContext:
    runAsUser: 0

ports:
  http: 15133

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

nodeSelector: {}
tolerations: []
affinity: {}

