apiVersion: skyhook.nvidia.com/v1alpha1
kind: Skyhook
metadata:
  labels:
    app.kubernetes.io/part-of: skyhook-operator
    app.kubernetes.io/created-by: skyhook-operator
  name: skyhook-gpuhealth
  annotations:
    skyhook.nvidia.com/pause: "false"
    skyhook.nvidia.com/disable: "false"
spec:
  packages:
    gpuhealth:
      image: nvcr.io/0753215517602916/gpu-health/gpuhealth-skyhook
      version: 0.0.1
      env:
        - name: GPUHEALTH_VERSION
          value: 0.0.1
        - name: GPUHEALTH_ENDPOINT
          value: https://data.us-east-1.dev.gpuhealth.nvidia.com
        - name: GPUHEALTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: gpuhealth-enroll-secret
              key: token
      configMap:
        gpuhealth.config: |-
          GPUHEALTH_RETRY_MAX_ATTEMPTS="5"
