name: CI - Unit Tests

on:
  push:
    branches: ["**"]
    tags: ['*.*.*']

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    if: github.ref != 'refs/heads/main'
    name: Unit Tests (Dev)
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: Run unit tests
        run: |
          echo "Running unit tests for dev branch..."
          KMSG_FILE_PATH=/dev/null ./scripts/tests-unit.sh

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-dev
          path: coverage.txt
          if-no-files-found: warn
          retention-days: 1
